name: Deploy NestJS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build Image
        shell: cmd
        run: docker compose build --no-cache

      - name: Stop Container
        shell: cmd
        run: docker compose down

      - name: Start Container
        shell: cmd
        run: docker compose up -d

      - name: Remove Unused Images
        shell: cmd
        run: docker image prune -f
