name: Deploy NestJS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v4

      - name: Check Docker
        run: |
          docker version
          docker context ls
          docker ps

      - name: Build Image
        run: docker compose build --no-cache

      - name: Stop Container
        continue-on-error: true
        run: docker compose down

      - name: Start Container
        run: docker compose up -d

      - name: Remove Unused Images
        run: docker image prune -f